# Client Configuration Template
# This file defines all the variables needed to generate a custom CLAUDE.md for each client

client_info:
  name: "{{CLIENT_NAME}}"
  description: "{{BUSINESS_DESCRIPTION}}"
  solution_category: "{{SOLUTION_CATEGORY}}"
  target_audience: "{{TARGET_AUDIENCE}}"
  target_descriptor: "{{TARGET_DESCRIPTOR}}"  # e.g., "contractor", "agency", "consultant"

paths:
  transcript_path: "/Users/{{USERNAME}}/Desktop/{{PROJECT_DIR}}/transcripts/"
  background_file: "/Users/{{USERNAME}}/Desktop/{{PROJECT_DIR}}/{{CLIENT_NAME}}_background.md"
  output_path: "/Users/{{USERNAME}}/Desktop/{{PROJECT_DIR}}/analysis/"
  master_analysis_file: "Transcript_analysis_extensive_{{YEAR}}.md"
  final_analysis_file: "Transcript_analysis_extensive_{{YEAR}}_FINAL.md"

business_metrics:
  current_stats: "{{CURRENT_STATS}}"  # e.g., "15% higher close rates reported, $3-10K average upsells"
  volume_metrics: "{{VOLUME_METRICS}}"  # e.g., "10,000+ contractors use platform"
  pricing_info: "{{PRICING_INFO}}"  # e.g., "Starting at $249/month for 4 users"
  sales_process: "{{SALES_PROCESS_INFO}}"  # e.g., "Demo-based sales, common objections include..."

awareness_stages:
  problem_aware:
    indicators:
      - "{{PROBLEM_INDICATOR_1}}"
      - "{{PROBLEM_INDICATOR_2}}"
      - "{{PROBLEM_INDICATOR_3}}"
    pain_points:
      - "{{PAIN_POINT_1}}"
      - "{{PAIN_POINT_2}}"
    search_terms: "{{PROBLEM_AWARE_SEARCH_TERMS}}"
    example: "{{PROBLEM_AWARE_EXAMPLE}}"

  solution_aware:
    needs:
      - "{{SOLUTION_NEED_1}}"
      - "{{SOLUTION_NEED_2}}"
    comparisons: "{{SOLUTION_COMPARISONS}}"
    search_terms: "{{SOLUTION_AWARE_SEARCH_TERMS}}"
    requirements: "{{SOLUTION_REQUIREMENTS}}"
    example: "{{SOLUTION_AWARE_EXAMPLE}}"

  product_aware:
    behaviors:
      - "{{PRODUCT_BEHAVIOR_1}}"
      - "{{PRODUCT_BEHAVIOR_2}}"
    search_terms: "{{PRODUCT_AWARE_SEARCH_TERMS}}"
    example: "{{PRODUCT_AWARE_EXAMPLE}}"

competitors:
  main_competitors:
    - name: "{{COMPETITOR_1}}"
      description: "{{COMPETITOR_1_DESC}}"
    - name: "{{COMPETITOR_2}}"
      description: "{{COMPETITOR_2_DESC}}"
  
differentiation:
  points:
    - "{{DIFF_POINT_1}}"
    - "{{DIFF_POINT_2}}"

transcripts:
  total: {{TOTAL_TRANSCRIPTS}}
  batch_size: 10
  date_range: "{{DATE_RANGE}}"